services:
  db:
    image: mysql:8.0
    container_name: samplevault-db-mock
    environment:
      MYSQL_ROOT_PASSWORD: mockpassword
      MYSQL_DATABASE: samplevault_mock
      MYSQL_USER: mockuser
      MYSQL_PASSWORD: mockpassword

  backend:
    environment:
      - DB_HOST=db
      - DB_USER=mockuser
      - DB_PASS=mockpassword
      - DB_NAME=samplevault_mock
      - NODE_ENV=mock